name: Dependabot auto-merge
on: pull_request
jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: mlm-games/ci/.github/workflows/dependabot-auto-merge.yml@v1
